/**
 * IntelliSense for the languages Monaco ships no language worker for.
 *
 * Monaco's own workers cover TypeScript, JavaScript and JSON — real type
 * checking, hover, signature help and diagnostics. Every other language in the
 * runner (Python, C, Java, …) has a grammar for syntax highlighting but no
 * worker, so out of the box there is not a single completion.
 *
 * This module is the substitute. For each language it carries:
 *
 *   keywords    reserved words
 *   types       class and type names
 *   constants   true/false/null and other named values
 *   functions   built-ins with signatures, e.g. "range(start, stop, step)"
 *   snippets    templates with tab stops, e.g. "for … in …"
 *   members     methods offered after a `.`
 *
 * It is deliberately data, not logic — `runner-editor.tsx` turns all of it into
 * Monaco providers. Nothing here is language-server grade: it cannot resolve a
 * receiver's real type, so `members` after a `.` is the union of what the
 * language's common types offer. That is still the difference between a text box
 * and a small IDE.
 *
 * Snippet bodies use Monaco's snippet syntax: `${1:placeholder}` is a tab stop,
 * `$0` the final cursor. They are written as single-quoted strings — a template
 * literal would try to interpolate `${1:…}`.
 */

export interface Snippet {
  /** What the user types to see it, e.g. "for". */
  label: string;
  /** Template body with `${1:placeholder}` tab stops. */
  body: string;
  /** Overrides the default "snippet" detail line. */
  detail?: string;
}

export interface LanguageIntellisense {
  keywords: string[];
  types?: string[];
  constants?: string[];
  /** `"name(param, param)"` — the parenthesised part becomes the signature. */
  functions?: string[];
  snippets?: Snippet[];
  /** `"name(param)"` entries offered after a `.`. */
  members?: string[];
}

export const LANGUAGE_INTELLISENSE: Record<string, LanguageIntellisense> = {
  python: {
    keywords: [
      'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await',
      'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except',
      'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is',
      'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try',
      'while', 'with', 'yield',
    ],
    types: [
      'int', 'float', 'str', 'bool', 'list', 'dict', 'set', 'frozenset',
      'tuple', 'bytes', 'bytearray', 'complex', 'object', 'type', 'range',
      'slice', 'memoryview',
    ],
    constants: [
      'True', 'False', 'None', 'NotImplemented', 'Ellipsis', '__name__',
      '__file__', '__doc__', '__main__',
    ],
    functions: [
      'abs(x)', 'all(iterable)', 'any(iterable)', 'ascii(obj)', 'bin(x)',
      'bool(x)', 'bytearray(source)', 'bytes(source)', 'callable(obj)',
      'chr(i)', 'classmethod(func)', 'complex(real, imag)', 'delattr(obj, name)',
      'dict(**kwargs)', 'dir(obj)', 'divmod(a, b)', 'enumerate(iterable, start=0)',
      'eval(expression)', 'exec(source)', 'filter(function, iterable)',
      'float(x)', 'format(value, format_spec)', 'frozenset(iterable)',
      'getattr(object, name, default)', 'globals()', 'hasattr(object, name)',
      'hash(obj)', 'help(obj)', 'hex(x)', 'id(obj)', 'input(prompt)',
      'int(x, base=10)', 'isinstance(obj, classinfo)', 'issubclass(cls, classinfo)',
      'iter(iterable)', 'len(obj)', 'list(iterable)', 'locals()',
      'map(function, iterable)', 'max(iterable, key=None)', 'min(iterable, key=None)',
      'next(iterator, default)', 'object()', 'oct(x)', 'open(file, mode="r")',
      'ord(c)', 'pow(base, exp, mod)', 'print(*objects, sep=" ", end="\\n")',
      'property(fget, fset, fdel)', 'range(start, stop, step)', 'repr(obj)',
      'reversed(sequence)', 'round(number, ndigits=None)', 'set(iterable)',
      'setattr(object, name, value)', 'slice(start, stop, step)',
      'sorted(iterable, key=None, reverse=False)', 'staticmethod(func)',
      'str(object)', 'sum(iterable, start=0)', 'super()', 'tuple(iterable)',
      'type(object)', 'vars(obj)', 'zip(*iterables)',
    ],
    snippets: [
      { label: 'def', body: 'def ${1:name}(${2:args}):\n    ${3:pass}' },
      { label: 'class', body: 'class ${1:Name}:\n    def __init__(self${2:, args}):\n        ${3:pass}' },
      { label: 'if', body: 'if ${1:condition}:\n    ${2:pass}' },
      { label: 'ifmain', body: 'if __name__ == "__main__":\n    ${1:main()}' },
      { label: 'for', body: 'for ${1:item} in ${2:iterable}:\n    ${3:pass}' },
      { label: 'while', body: 'while ${1:condition}:\n    ${2:pass}' },
      { label: 'try', body: 'try:\n    ${1:pass}\nexcept ${2:Exception} as ${3:error}:\n    ${4:raise}' },
      { label: 'with', body: 'with ${1:expression} as ${2:name}:\n    ${3:pass}' },
      { label: 'lambda', body: 'lambda ${1:args}: ${2:expression}' },
      { label: 'main', body: 'def main():\n    ${1:pass}\n\n\nif __name__ == "__main__":\n    main()' },
      { label: 'listcomp', body: '[${1:expression} for ${2:item} in ${3:iterable}]' },
      { label: 'dictcomp', body: '{${1:key}: ${2:value} for ${3:item} in ${4:iterable}}' },
      { label: 'readfile', body: 'with open(${1:filename}, "${2:r}") as ${3:file}:\n    ${4:data = file.read()}' },
    ],
    members: [
      'append(item)', 'extend(iterable)', 'insert(index, item)', 'remove(item)',
      'pop(index)', 'clear()', 'index(item)', 'count(item)',
      'sort(key=None, reverse=False)', 'reverse()', 'copy()',
      'add(item)', 'discard(item)', 'union(other)', 'intersection(other)',
      'difference(other)', 'issubset(other)', 'issuperset(other)', 'update(other)',
      'get(key, default)', 'keys()', 'values()', 'items()',
      'setdefault(key, default)', 'popitem()', 'fromkeys(keys)',
      'upper()', 'lower()', 'strip(chars)', 'lstrip(chars)', 'rstrip(chars)',
      'split(sep)', 'rsplit(sep)', 'join(iterable)', 'replace(old, new)',
      'find(sub)', 'rfind(sub)', 'startswith(prefix)', 'endswith(suffix)',
      'format(*args)', 'capitalize()', 'title()', 'center(width)',
      'ljust(width)', 'rjust(width)', 'zfill(width)', 'isdigit()', 'isalpha()',
      'isalnum()', 'isspace()', 'islower()', 'isupper()', 'encode(encoding)',
      'casefold()', 'partition(sep)', 'splitlines()', 'swapcase()',
      'read(size)', 'readline()', 'readlines()', 'write(text)',
      'writelines(lines)', 'close()', 'seek(offset)', 'flush()', 'tell()',
    ],
  },

  c: {
    keywords: [
      'auto', 'break', 'case', 'char', 'const', 'continue', 'default', 'do',
      'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if',
      'inline', 'int', 'long', 'register', 'restrict', 'return', 'short',
      'signed', 'sizeof', 'static', 'struct', 'switch', 'typedef', 'union',
      'unsigned', 'void', 'volatile', 'while',
    ],
    types: [
      'size_t', 'ssize_t', 'ptrdiff_t', 'int8_t', 'int16_t', 'int32_t',
      'int64_t', 'uint8_t', 'uint16_t', 'uint32_t', 'uint64_t', 'bool',
      'wchar_t', 'FILE', 'time_t', 'va_list',
    ],
    constants: [
      'NULL', 'EOF', 'EXIT_SUCCESS', 'EXIT_FAILURE', 'true', 'false',
      'SEEK_SET', 'SEEK_CUR', 'SEEK_END', 'stdin', 'stdout', 'stderr', 'BUFSIZ',
    ],
    functions: [
      'printf(const char* format, ...)', 'fprintf(FILE* stream, const char* format, ...)',
      'sprintf(char* str, const char* format, ...)', 'snprintf(char* str, size_t size, const char* format, ...)',
      'scanf(const char* format, ...)', 'fscanf(FILE* stream, const char* format, ...)',
      'sscanf(const char* str, const char* format, ...)', 'puts(const char* s)',
      'fputs(const char* s, FILE* stream)', 'putchar(int c)', 'getchar()',
      'fgets(char* s, int size, FILE* stream)', 'fgetc(FILE* stream)',
      'fputc(int c, FILE* stream)', 'fopen(const char* path, const char* mode)',
      'fclose(FILE* stream)', 'fread(void* ptr, size_t size, size_t n, FILE* stream)',
      'fwrite(const void* ptr, size_t size, size_t n, FILE* stream)',
      'fseek(FILE* stream, long offset, int whence)', 'ftell(FILE* stream)',
      'rewind(FILE* stream)', 'fflush(FILE* stream)',
      'malloc(size_t size)', 'calloc(size_t n, size_t size)',
      'realloc(void* ptr, size_t size)', 'free(void* ptr)',
      'exit(int status)', 'abort()', 'atexit(void (*func)(void))',
      'atoi(const char* s)', 'atol(const char* s)', 'atof(const char* s)',
      'strtol(const char* s, char** end, int base)', 'strtod(const char* s, char** end)',
      'strlen(const char* s)', 'strcpy(char* dest, const char* src)',
      'strncpy(char* dest, const char* src, size_t n)',
      'strcat(char* dest, const char* src)', 'strncat(char* dest, const char* src, size_t n)',
      'strcmp(const char* a, const char* b)', 'strncmp(const char* a, const char* b, size_t n)',
      'strstr(const char* haystack, const char* needle)', 'strchr(const char* s, int c)',
      'strrchr(const char* s, int c)', 'strtok(char* s, const char* delim)',
      'memcpy(void* dest, const void* src, size_t n)', 'memmove(void* dest, const void* src, size_t n)',
      'memset(void* ptr, int value, size_t n)', 'memcmp(const void* a, const void* b, size_t n)',
      'qsort(void* base, size_t n, size_t size, int (*cmp)(const void*, const void*))',
      'assert(condition)', 'abs(int x)', 'labs(long x)',
      'isalpha(int c)', 'isdigit(int c)', 'isspace(int c)', 'tolower(int c)', 'toupper(int c)',
      'sqrt(double x)', 'pow(double base, double exp)', 'floor(double x)', 'ceil(double x)',
      'sin(double x)', 'cos(double x)', 'rand()', 'srand(unsigned int seed)',
    ],
    snippets: [
      { label: 'main', body: 'int main(void) {\n    ${1:printf("Hello, world!\\n");}\n    return 0;\n}' },
      { label: 'for', body: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    ${3}\n}' },
      { label: 'while', body: 'while (${1:condition}) {\n    ${2}\n}' },
      { label: 'if', body: 'if (${1:condition}) {\n    ${2}\n}' },
      { label: 'include', body: '#include <${1:stdio.h}>' },
      { label: 'printf', body: 'printf("${1:%d}\\n", ${2:value});' },
      { label: 'scanf', body: 'scanf("${1:%d}", &${2:value});' },
      { label: 'struct', body: 'typedef struct {\n    ${1:int field};\n} ${2:Name};' },
      { label: 'switch', body: 'switch (${1:value}) {\n    case ${2:0}:\n        ${3:break;}\n    default:\n        ${4:break;}\n}' },
    ],
  },

  cpp: {
    keywords: [
      'alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor',
      'bool', 'break', 'case', 'catch', 'char', 'char8_t', 'char16_t',
      'char32_t', 'class', 'compl', 'concept', 'const', 'const_cast',
      'continue', 'co_await', 'co_return', 'co_yield', 'decltype', 'default',
      'delete', 'do', 'double', 'dynamic_cast', 'else', 'enum', 'explicit',
      'export', 'extern', 'false', 'float', 'for', 'friend', 'goto', 'if',
      'inline', 'int', 'long', 'mutable', 'namespace', 'new', 'noexcept',
      'not', 'not_eq', 'nullptr', 'operator', 'or', 'or_eq', 'private',
      'protected', 'public', 'register', 'reinterpret_cast', 'requires',
      'return', 'short', 'signed', 'sizeof', 'static', 'static_assert',
      'static_cast', 'struct', 'switch', 'template', 'this', 'thread_local',
      'throw', 'true', 'try', 'typedef', 'typeid', 'typename', 'union',
      'unsigned', 'using', 'virtual', 'void', 'volatile', 'wchar_t', 'while',
    ],
    types: [
      'std::string', 'std::vector', 'std::map', 'std::unordered_map',
      'std::set', 'std::unordered_set', 'std::pair', 'std::tuple',
      'std::optional', 'std::variant', 'std::shared_ptr', 'std::unique_ptr',
      'std::weak_ptr', 'std::function', 'std::array', 'std::deque',
      'std::list', 'std::queue', 'std::stack', 'std::priority_queue',
      'std::istream', 'std::ostream', 'std::stringstream', 'std::size_t', 'int64_t',
    ],
    constants: [
      'nullptr', 'true', 'false', 'std::endl', 'std::string::npos',
      'INT_MAX', 'INT_MIN', 'LLONG_MAX', 'M_PI',
    ],
    functions: [
      'std::cout << value', 'std::cin >> value', 'std::cerr << value',
      'std::getline(std::istream& is, std::string& str)',
      'std::sort(std::begin(v), std::end(v))', 'std::reverse(std::begin(v), std::end(v))',
      'std::find(std::begin(v), std::end(v), value)',
      'std::count(std::begin(v), std::end(v), value)',
      'std::count_if(std::begin(v), std::end(v), predicate)',
      'std::min_element(std::begin(v), std::end(v))', 'std::max_element(std::begin(v), std::end(v))',
      'std::accumulate(std::begin(v), std::end(v), 0)',
      'std::transform(std::begin(v), std::end(v), std::back_inserter(out), fn)',
      'std::max(a, b)', 'std::min(a, b)', 'std::abs(x)', 'std::swap(a, b)',
      'std::move(value)', 'std::forward<T>(value)',
      'std::sqrt(x)', 'std::pow(base, exp)', 'std::floor(x)', 'std::ceil(x)',
      'std::to_string(value)', 'std::stoi(str)', 'std::stol(str)', 'std::stod(str)',
      'std::make_shared<T>(args)', 'std::make_unique<T>(args)',
      'std::make_pair(a, b)', 'std::make_tuple(args)',
      'std::lower_bound(std::begin(v), std::end(v), value)',
      'std::upper_bound(std::begin(v), std::end(v), value)',
      'std::begin(v)', 'std::end(v)', 'std::size(v)', 'std::size_t',
    ],
    snippets: [
      { label: 'main', body: '#include <iostream>\n\nint main() {\n    ${1:std::cout << "Hello, world!" << std::endl;}\n    return 0;\n}' },
      { label: 'for', body: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ++${1:i}) {\n    ${3}\n}' },
      { label: 'foreach', body: 'for (const auto& ${1:item} : ${2:container}) {\n    ${3}\n}' },
      { label: 'while', body: 'while (${1:condition}) {\n    ${2}\n}' },
      { label: 'if', body: 'if (${1:condition}) {\n    ${2}\n}' },
      { label: 'cout', body: 'std::cout << ${1:value} << std::endl;' },
      { label: 'cin', body: 'std::cin >> ${1:value};' },
      { label: 'vector', body: 'std::vector<${1:int}> ${2:name}(${3:n});' },
      { label: 'class', body: 'class ${1:Name} {\npublic:\n    ${1:Name}(${2});\n\nprivate:\n    ${3};\n};' },
      { label: 'struct', body: 'struct ${1:Name} {\n    ${2:int field};\n};' },
      { label: 'include', body: '#include <${1:iostream}>' },
      { label: 'sort', body: 'std::sort(${1:v}.begin(), ${1:v}.end());' },
    ],
    members: [
      'size()', 'length()', 'empty()', 'clear()', 'append(s)', 'substr(pos, len)',
      'find(s)', 'rfind(s)', 'at(i)', 'c_str()', 'begin()', 'end()',
      'push_back(value)', 'pop_back()', 'front()', 'back()', 'resize(n)',
      'reserve(n)', 'capacity()', 'insert(pos, value)', 'erase(pos)',
      'emplace_back(args)', 'data()', 'replace(pos, len, s)',
      'count(key)', 'contains(key)', 'emplace(key, value)', 'erase(key)',
      'equal_range(key)', 'lower_bound(key)', 'upper_bound(key)',
      'top()', 'push(value)', 'pop()', 'first', 'second', 'get<i>()',
    ],
  },

  java: {
    keywords: [
      'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch',
      'char', 'class', 'const', 'continue', 'default', 'do', 'double',
      'else', 'enum', 'extends', 'final', 'finally', 'float', 'for', 'goto',
      'if', 'implements', 'import', 'instanceof', 'int', 'interface', 'long',
      'native', 'new', 'package', 'private', 'protected', 'public', 'record',
      'return', 'sealed', 'short', 'static', 'strictfp', 'super', 'switch',
      'synchronized', 'this', 'throw', 'throws', 'transient', 'try', 'var',
      'void', 'volatile', 'while', 'yield',
    ],
    types: [
      'String', 'Integer', 'Double', 'Long', 'Float', 'Short', 'Byte',
      'Boolean', 'Character', 'Object', 'Number', 'Math', 'Arrays',
      'Collections', 'ArrayList', 'LinkedList', 'HashMap', 'TreeMap',
      'HashSet', 'TreeSet', 'List', 'Map', 'Set', 'Queue', 'Deque',
      'Iterator', 'Scanner', 'StringBuilder', 'StringBuffer', 'Optional',
      'Stream', 'Comparator', 'Random', 'BigInteger', 'BigDecimal',
      'LocalDate', 'LocalDateTime', 'File', 'Path', 'Exception',
      'RuntimeException', 'IOException', 'Thread', 'Runnable',
    ],
    constants: [
      'true', 'false', 'null', 'Integer.MAX_VALUE', 'Integer.MIN_VALUE',
      'Long.MAX_VALUE', 'Long.MIN_VALUE', 'Double.MAX_VALUE', 'Double.MIN_VALUE',
      'Math.PI', 'Math.E', 'System.out', 'System.in', 'System.err',
    ],
    functions: [
      'System.out.println(value)', 'System.out.print(value)',
      'System.out.printf(format, args)', 'System.out.format(format, args)',
      'Math.abs(x)', 'Math.max(a, b)', 'Math.min(a, b)', 'Math.pow(a, b)',
      'Math.sqrt(x)', 'Math.floor(x)', 'Math.ceil(x)', 'Math.round(x)',
      'Math.random()', 'Math.toIntExact(value)',
      'Integer.parseInt(str)', 'Integer.valueOf(str)', 'Integer.toBinaryString(x)',
      'Integer.toHexString(x)', 'Integer.compare(a, b)',
      'Long.parseLong(str)', 'Double.parseDouble(str)', 'Double.valueOf(str)',
      'Boolean.parseBoolean(str)', 'Character.isDigit(c)', 'Character.isLetter(c)',
      'Character.toUpperCase(c)', 'Character.toLowerCase(c)',
      'String.valueOf(value)', 'String.format(format, args)', 'String.join(delimiter, elements)',
      'Arrays.sort(array)', 'Arrays.toString(array)', 'Arrays.asList(elements)',
      'Arrays.fill(array, value)', 'Arrays.copyOf(array, length)',
      'Arrays.binarySearch(array, key)', 'Arrays.stream(array)',
      'Collections.sort(list)', 'Collections.reverse(list)', 'Collections.max(list)',
      'Collections.min(list)', 'Collections.shuffle(list)', 'Collections.emptyList()',
      'Objects.equals(a, b)', 'Objects.requireNonNull(value)',
      'Files.readString(path)', 'Files.writeString(path, content)',
      'Paths.get(first, more)',
    ],
    snippets: [
      { label: 'main', body: 'public static void main(String[] args) {\n    ${1}\n}' },
      { label: 'class', body: 'public class ${1:Main} {\n    ${2}\n}' },
      { label: 'sout', body: 'System.out.println(${1:value});' },
      { label: 'soutv', body: 'System.out.println("${1:name} = " + ${1:name});' },
      { label: 'soutf', body: 'System.out.printf("${1:%s}\\n", ${2:value});' },
      { label: 'for', body: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    ${3}\n}' },
      { label: 'foreach', body: 'for (${1:String} ${2:item} : ${3:items}) {\n    ${4}\n}' },
      { label: 'while', body: 'while (${1:condition}) {\n    ${2}\n}' },
      { label: 'if', body: 'if (${1:condition}) {\n    ${2}\n}' },
      { label: 'try', body: 'try {\n    ${1}\n} catch (${2:Exception} e) {\n    ${3:e.printStackTrace();}\n}' },
      { label: 'scanner', body: 'Scanner ${1:scanner} = new Scanner(System.in);\n${2:int n = ${1:scanner}.nextInt();}' },
      { label: 'list', body: 'List<${1:Integer}> ${2:list} = new ArrayList<>();' },
      { label: 'map', body: 'Map<${1:String}, ${2:Integer}> ${3:map} = new HashMap<>();' },
      { label: 'set', body: 'Set<${1:Integer}> ${2:set} = new HashSet<>();' },
      { label: 'array', body: 'int[] ${1:arr} = new int[${2:n}];' },
    ],
    members: [
      'length()', 'charAt(index)', 'substring(begin, end)', 'indexOf(str)',
      'lastIndexOf(str)', 'toUpperCase()', 'toLowerCase()', 'trim()',
      'strip()', 'split(regex)', 'replace(target, replacement)',
      'replaceAll(regex, replacement)', 'equals(obj)', 'equalsIgnoreCase(str)',
      'contains(str)', 'startsWith(prefix)', 'endsWith(suffix)', 'isEmpty()',
      'isBlank()', 'toCharArray()', 'compareTo(str)', 'concat(str)',
      'matches(regex)', 'repeat(count)', 'format(args)',
      'add(element)', 'get(index)', 'set(index, element)', 'remove(index)',
      'size()', 'clear()', 'indexOf(element)', 'addAll(collection)',
      'containsAll(collection)', 'iterator()', 'stream()', 'sort(comparator)',
      'toArray()', 'removeIf(predicate)', 'forEach(action)',
      'put(key, value)', 'containsKey(key)', 'containsValue(value)',
      'keySet()', 'values()', 'entrySet()', 'getOrDefault(key, defaultValue)',
      'putIfAbsent(key, value)', 'merge(key, value, remappingFunction)',
      'computeIfAbsent(key, mappingFunction)',
      'nextInt()', 'nextLong()', 'nextDouble()', 'next()', 'nextLine()',
      'nextBoolean()', 'hasNext()', 'hasNextInt()', 'hasNextLine()', 'close()',
      'append(value)', 'toString()', 'insert(offset, str)', 'reverse()',
      'deleteCharAt(index)', 'setLength(length)',
      'matches(pattern)', 'find()', 'group()', 'start()', 'end()',
      'stream()', 'filter(predicate)', 'map(function)', 'collect(collector)',
      'forEach(action)', 'count()', 'sorted()', 'distinct()', 'limit(n)',
      'skip(n)', 'reduce(identity, accumulator)', 'toList()',
    ],
  },

  csharp: {
    keywords: [
      'abstract', 'as', 'base', 'bool', 'break', 'byte', 'case', 'catch',
      'char', 'checked', 'class', 'const', 'continue', 'decimal', 'default',
      'delegate', 'do', 'double', 'else', 'enum', 'event', 'explicit',
      'extern', 'false', 'finally', 'fixed', 'float', 'for', 'foreach',
      'goto', 'if', 'implicit', 'in', 'int', 'interface', 'internal', 'is',
      'lock', 'long', 'namespace', 'new', 'null', 'object', 'operator', 'out',
      'override', 'params', 'private', 'protected', 'public', 'readonly',
      'record', 'ref', 'return', 'sbyte', 'sealed', 'short', 'sizeof',
      'stackalloc', 'static', 'string', 'struct', 'switch', 'this', 'throw',
      'true', 'try', 'typeof', 'uint', 'ulong', 'unchecked', 'unsafe',
      'ushort', 'using', 'var', 'virtual', 'void', 'volatile', 'while',
      'async', 'await', 'dynamic', 'nameof', 'when', 'yield',
    ],
    types: [
      'String', 'Int32', 'Int64', 'Double', 'Decimal', 'Boolean', 'Char',
      'Object', 'Math', 'Console', 'List', 'Dictionary', 'HashSet', 'Queue',
      'Stack', 'Array', 'Enumerable', 'StringBuilder', 'DateTime',
      'TimeSpan', 'Exception', 'Task', 'IEnumerable', 'IList', 'IDictionary',
      'Nullable', 'Random', 'Regex',
    ],
    constants: [
      'true', 'false', 'null', 'int.MaxValue', 'int.MinValue',
      'double.MaxValue', 'double.MinValue', 'Math.PI', 'Math.E',
      'Console.Out', 'Environment.NewLine',
    ],
    functions: [
      'Console.WriteLine(value)', 'Console.Write(value)',
      'Console.ReadLine()', 'Console.ReadKey()',
      'Math.Abs(value)', 'Math.Max(a, b)', 'Math.Min(a, b)', 'Math.Pow(x, y)',
      'Math.Sqrt(x)', 'Math.Floor(x)', 'Math.Ceiling(x)', 'Math.Round(x)',
      'int.Parse(str)', 'int.TryParse(str, out result)', 'double.Parse(str)',
      'Convert.ToInt32(value)', 'Convert.ToString(value)', 'Convert.ToDouble(value)',
      'String.Format(format, args)', 'String.Join(separator, values)',
      'String.IsNullOrEmpty(value)', 'String.IsNullOrWhiteSpace(value)',
      'Array.Sort(array)', 'Array.IndexOf(array, value)',
      'Enumerable.Range(start, count)', 'Enumerable.Repeat(value, count)',
      'Task.Delay(milliseconds)', 'Task.Run(action)',
    ],
    snippets: [
      { label: 'main', body: 'static void Main(string[] args) {\n    ${1}\n}' },
      { label: 'class', body: 'class ${1:Program} {\n    ${2}\n}' },
      { label: 'cw', body: 'Console.WriteLine(${1:value});' },
      { label: 'cwf', body: 'Console.WriteLine($"{${1:value}}");' },
      { label: 'for', body: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    ${3}\n}' },
      { label: 'foreach', body: 'foreach (var ${1:item} in ${2:collection}) {\n    ${3}\n}' },
      { label: 'while', body: 'while (${1:condition}) {\n    ${2}\n}' },
      { label: 'if', body: 'if (${1:condition}) {\n    ${2}\n}' },
      { label: 'try', body: 'try {\n    ${1}\n} catch (${2:Exception} ex) {\n    ${3:Console.WriteLine(ex.Message);}\n}' },
      { label: 'list', body: 'var ${1:list} = new List<${2:int}>();' },
      { label: 'dict', body: 'var ${1:map} = new Dictionary<${2:string}, ${3:int}>();' },
    ],
    members: [
      'Length', 'Count', 'Trim()', 'ToUpper()', 'ToLower()', 'Substring(start, length)',
      'IndexOf(value)', 'Contains(value)', 'Replace(old, new)', 'Split(separator)',
      'StartsWith(value)', 'EndsWith(value)', 'ToCharArray()', 'IsNullOrEmpty(value)',
      'Add(item)', 'Remove(item)', 'Clear()', 'Contains(item)', 'ForEach(action)',
      'ToArray()', 'Sort()', 'Reverse()', 'Where(predicate)', 'Select(selector)',
      'OrderBy(keySelector)', 'First()', 'FirstOrDefault()', 'Any()', 'All(predicate)',
      'Sum()', 'Max()', 'Min()', 'Average()', 'ToList()', 'Distinct()', 'Take(n)', 'Skip(n)',
      'Keys', 'Values', 'TryGetValue(key, out value)', 'AddOrUpdate(key, value)',
      'ToString()', 'Equals(obj)', 'GetType()', 'GetHashCode()',
      'Append(value)', 'Insert(index, value)', 'RemoveAt(index)',
    ],
  },

  go: {
    keywords: [
      'break', 'case', 'chan', 'const', 'continue', 'default', 'defer',
      'else', 'fallthrough', 'for', 'func', 'go', 'goto', 'if', 'import',
      'interface', 'map', 'package', 'range', 'return', 'select', 'struct',
      'switch', 'type', 'var',
    ],
    types: [
      'string', 'int', 'int8', 'int16', 'int32', 'int64', 'uint', 'uint8',
      'uint16', 'uint32', 'uint64', 'float32', 'float64', 'complex64',
      'complex128', 'byte', 'rune', 'bool', 'error', 'any', 'interface{}',
      '[]byte', 'sync.Mutex', 'sync.WaitGroup', 'time.Duration', 'time.Time',
    ],
    constants: ['true', 'false', 'nil', 'iota', 'math.Pi', 'math.MaxInt', 'time.Second'],
    functions: [
      'fmt.Println(args...)', 'fmt.Printf(format, args...)',
      'fmt.Sprintf(format, args...)', 'fmt.Print(args...)',
      'fmt.Scan(args...)', 'fmt.Scanln(args...)', 'fmt.Sscanf(str, format, args...)',
      'fmt.Errorf(format, args...)', 'fmt.Fprintln(w, args...)',
      'len(v)', 'cap(v)', 'make(type, size)', 'new(type)', 'append(slice, elems...)',
      'copy(dst, src)', 'delete(map, key)', 'close(ch)', 'panic(v)', 'recover()',
      'print(args...)', 'println(args...)', 'complex(real, imag)', 'real(c)',
      'imag(c)', 'min(a, b)', 'max(a, b)', 'clear(m)',
      'strings.Split(s, sep)', 'strings.Join(elems, sep)', 'strings.Contains(s, substr)',
      'strings.HasPrefix(s, prefix)', 'strings.HasSuffix(s, suffix)',
      'strings.ToUpper(s)', 'strings.ToLower(s)', 'strings.TrimSpace(s)',
      'strings.ReplaceAll(s, old, new)', 'strings.Index(s, substr)',
      'strings.Repeat(s, count)', 'strings.Fields(s)',
      'strconv.Itoa(i)', 'strconv.Atoi(s)', 'strconv.ParseInt(s, base, bitSize)',
      'strconv.ParseFloat(s, bitSize)', 'strconv.FormatInt(i, base)',
      'sort.Ints(slice)', 'sort.Strings(slice)', 'sort.Slice(slice, less)',
      'sort.Search(n, f)',
      'os.Exit(code)', 'os.Args', 'os.Stdin', 'os.Stdout',
      'errors.New(text)', 'errors.Is(err, target)', 'errors.As(err, target)',
      'time.Sleep(d)', 'time.Now()', 'time.Since(t)',
      'sync.WaitGroup.Add(delta)', 'math.Abs(x)', 'math.Sqrt(x)', 'math.Pow(x, y)',
      'math.Max(a, b)', 'math.Min(a, b)', 'math.Floor(x)', 'math.Ceil(x)',
    ],
    snippets: [
      { label: 'main', body: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t${1:fmt.Println("Hello, world!")}\n}' },
      { label: 'func', body: 'func ${1:name}(${2:args}) ${3:error} {\n\t${4}\n\treturn nil\n}' },
      { label: 'for', body: 'for ${1:i := 0}; ${1:i} < ${2:n}; ${1:i}++ {\n\t${3}\n}' },
      { label: 'foreach', body: 'for ${1:i}, ${2:v} := range ${3:items} {\n\t${4}\n}' },
      { label: 'if', body: 'if ${1:err} != nil {\n\t${2:return err}\n}' },
      { label: 'switch', body: 'switch ${1:value} {\ncase ${2:option}:\n\t${3}\ndefault:\n\t${4}\n}' },
      { label: 'struct', body: 'type ${1:Name} struct {\n\t${2:Field} ${3:string}\n}' },
      { label: 'printf', body: 'fmt.Printf("${1:%v}\\n", ${2:value})' },
      { label: 'scanner', body: 'scanner := bufio.NewScanner(os.Stdin)\nfor scanner.Scan() {\n\t${1:fmt.Println(scanner.Text())}\n}' },
      { label: 'goroutine', body: 'go func() {\n\t${1}\n}()' },
    ],
    members: [
      'Len()', 'Cap()', 'String()', 'Error()', 'Append(value)',
      'Write(p)', 'Read(p)', 'Close()', 'Format(f)', 'Scan(state)',
      'Lock()', 'Unlock()', 'RLock()', 'RUnlock()', 'Done()',
      'Add(delta)', 'Wait()', 'Truncate(d)', 'Seconds()', 'Milliseconds()',
      'Nanoseconds()', 'Format(layout)', 'Unix()', 'Add(d)', 'Sub(t)',
      'IsZero()', 'Before(t)', 'After(t)', 'Day()', 'Month()', 'Year()',
    ],
  },

  rust: {
    keywords: [
      'as', 'async', 'await', 'break', 'const', 'continue', 'crate', 'dyn',
      'else', 'enum', 'extern', 'false', 'fn', 'for', 'if', 'impl', 'in',
      'let', 'loop', 'match', 'mod', 'move', 'mut', 'pub', 'ref', 'return',
      'self', 'Self', 'static', 'struct', 'super', 'trait', 'true', 'try',
      'type', 'unsafe', 'use', 'where', 'while',
    ],
    types: [
      'String', 'str', 'Vec', 'HashMap', 'HashSet', 'BTreeMap', 'BTreeSet',
      'Option', 'Result', 'Box', 'Rc', 'Arc', 'RefCell', 'Mutex', 'RwLock',
      'i8', 'i16', 'i32', 'i64', 'i128', 'isize', 'u8', 'u16', 'u32', 'u64',
      'u128', 'usize', 'f32', 'f64', 'bool', 'char', 'Ordering',
    ],
    constants: ['None', 'Some', 'Ok', 'Err', 'true', 'false', 'i32::MAX', 'u32::MAX', 'f64::INFINITY'],
    functions: [
      'println!(format, args...)', 'print!(format, args...)',
      'eprintln!(format, args...)', 'format!(format, args...)',
      'vec![elements...]', 'write!(writer, format, args...)',
      'String::new()', 'String::from(str)', 'Vec::new()', 'Vec::with_capacity(n)',
      'HashMap::new()', 'HashSet::new()',
      'Some(value)', 'None', 'Ok(value)', 'Err(error)',
      'Box::new(value)', 'Rc::new(value)', 'Arc::new(value)',
      'assert!(condition)', 'assert_eq!(left, right)', 'assert_ne!(left, right)',
      'panic!(message)', 'todo!()', 'unimplemented!()', 'unreachable!()',
      'dbg!(value)', 'matches!(value, pattern)',
      'std::mem::swap(a, b)', 'std::mem::replace(dest, src)',
      'std::cmp::max(a, b)', 'std::cmp::min(a, b)', 'std::cmp::Ordering',
      'parse::<T>()', 'to_string()', 'to_owned()',
    ],
    snippets: [
      { label: 'main', body: 'fn main() {\n    ${1:println!("Hello, world!");}\n}' },
      { label: 'fn', body: 'fn ${1:name}(${2:args}) -> ${3:ReturnType} {\n    ${4:todo!()}\n}' },
      { label: 'for', body: 'for ${1:item} in ${2:iterable} {\n    ${3}\n}' },
      { label: 'while', body: 'while ${1:condition} {\n    ${2}\n}' },
      { label: 'loop', body: 'loop {\n    ${1}\n}' },
      { label: 'match', body: 'match ${1:value} {\n    ${2:pattern} => ${3:result},\n    _ => ${4:todo!()},\n}' },
      { label: 'iflet', body: 'if let ${1:Some(value)} = ${2:expression} {\n    ${3}\n}' },
      { label: 'struct', body: '#[derive(Debug, Clone)]\nstruct ${1:Name} {\n    ${2:field}: ${3:String},\n}' },
      { label: 'impl', body: 'impl ${1:Name} {\n    fn ${2:new}(${3}) -> Self {\n        ${4:Self { }}\n    }\n}' },
      { label: 'test', body: '#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn ${1:it_works}() {\n        ${2:assert_eq!(2 + 2, 4);}\n    }\n}' },
    ],
    members: [
      'len()', 'is_empty()', 'push(value)', 'pop()', 'insert(index, value)',
      'remove(index)', 'clear()', 'iter()', 'iter_mut()', 'into_iter()',
      'get(index)', 'get_mut(index)', 'contains(&value)', 'sort()',
      'sort_by(comparator)', 'extend(iterable)', 'retain(predicate)',
      'first()', 'last()', 'join(separator)', 'split(separator)',
      'trim()', 'to_uppercase()', 'to_lowercase()', 'replace(from, to)',
      'starts_with(prefix)', 'ends_with(suffix)', 'chars()', 'bytes()',
      'parse()', 'clone()', 'unwrap()', 'expect(message)', 'unwrap_or(default)',
      'unwrap_or_else(f)', 'is_some()', 'is_none()', 'is_ok()', 'is_err()',
      'map(f)', 'and_then(f)', 'filter(predicate)', 'take()', 'as_ref()',
      'as_str()', 'to_string()', 'insert(key, value)', 'entry(key)',
      'keys()', 'values()', 'iter()', 'lock()', 'read()', 'write()',
    ],
  },

  php: {
    keywords: [
      'abstract', 'and', 'array', 'as', 'break', 'callable', 'case', 'catch',
      'class', 'clone', 'const', 'continue', 'declare', 'default', 'do',
      'echo', 'else', 'elseif', 'empty', 'enum', 'exit', 'extends', 'final',
      'finally', 'fn', 'for', 'foreach', 'function', 'global', 'goto', 'if',
      'implements', 'include', 'include_once', 'instanceof', 'insteadof',
      'interface', 'isset', 'list', 'match', 'namespace', 'new', 'or',
      'print', 'private', 'protected', 'public', 'readonly', 'require',
      'require_once', 'return', 'static', 'switch', 'throw', 'trait', 'try',
      'unset', 'use', 'var', 'while', 'xor', 'yield',
    ],
    types: ['string', 'int', 'float', 'bool', 'array', 'object', 'mixed', 'void', 'null', 'never', 'Closure', 'Generator', 'ArrayObject', 'DateTime', 'Exception', 'PDO'],
    constants: ['true', 'false', 'null', 'PHP_EOL', 'PHP_INT_MAX', 'PHP_INT_MIN', 'M_PI'],
    functions: [
      'echo value', 'print value', 'printf(format, args...)', 'sprintf(format, args...)',
      'var_dump(value)', 'print_r(value)', 'var_export(value)',
      'isset(value)', 'empty(value)', 'unset(value)', 'count(array)',
      'array(...)', 'in_array(needle, haystack)', 'array_map(callback, array)',
      'array_filter(array, callback)', 'array_push(array, value)',
      'array_pop(array)', 'array_shift(array)', 'array_unshift(array, value)',
      'array_keys(array)', 'array_values(array)', 'array_merge(...arrays)',
      'array_slice(array, offset, length)', 'array_search(needle, haystack)',
      'array_reverse(array)', 'array_unique(array)', 'array_sum(array)',
      'sort(array)', 'rsort(array)', 'usort(array, callback)', 'ksort(array)',
      'implode(separator, array)', 'explode(separator, string)',
      'strlen(string)', 'substr(string, offset, length)', 'str_replace(search, replace, subject)',
      'strpos(haystack, needle)', 'strtolower(string)', 'strtoupper(string)',
      'trim(string)', 'ltrim(string)', 'rtrim(string)', 'ucfirst(string)',
      'str_repeat(string, times)', 'str_split(string, length)', 'str_contains(haystack, needle)',
      'str_starts_with(haystack, needle)', 'str_ends_with(haystack, needle)',
      'preg_match(pattern, subject)', 'preg_replace(pattern, replacement, subject)',
      'json_encode(value)', 'json_decode(json, associative)',
      'intval(value)', 'floatval(value)', 'strval(value)', 'boolval(value)',
      'is_array(value)', 'is_string(value)', 'is_int(value)', 'is_null(value)',
      'max(values)', 'min(values)', 'abs(number)', 'round(number, precision)',
      'floor(number)', 'ceil(number)', 'pow(base, exp)', 'sqrt(number)',
      'rand(min, max)', 'mt_rand(min, max)', 'range(start, end)',
      'date(format, timestamp)', 'time()', 'file_get_contents(filename)',
      'file_put_contents(filename, data)', 'fopen(filename, mode)', 'fclose(handle)',
    ],
    snippets: [
      { label: 'php', body: '<?php\n\n${1:echo "Hello, world!\\n";}\n' },
      { label: 'function', body: 'function ${1:name}(${2:$args}): ${3:void} {\n    ${4}\n}' },
      { label: 'class', body: 'class ${1:Name} {\n    public function __construct(${2}) {\n        ${3}\n    }\n}' },
      { label: 'foreach', body: 'foreach (${1:$items} as ${2:$key} => ${3:$value}) {\n    ${4}\n}' },
      { label: 'for', body: 'for (${1:$i} = 0; ${1:$i} < ${2:$n}; ${1:$i}++) {\n    ${3}\n}' },
      { label: 'while', body: 'while (${1:$condition}) {\n    ${2}\n}' },
      { label: 'if', body: 'if (${1:$condition}) {\n    ${2}\n}' },
      { label: 'try', body: 'try {\n    ${1}\n} catch (${2:Exception} ${3:error}) {\n    ${4}\n}' },
      { label: 'vardump', body: 'var_dump(${1:$value});' },
      { label: 'assoc', body: '${1:$array} = [\n    ${2:"key" => "value",}\n];' },
    ],
    members: [
      '->length', '->count()', '->append(value)', '->isEmpty()',
      '->format(format)', '->modify(modifier)', '->getTimestamp()',
      '->setDate(year, month, day)', '->diff(other)',
      '->getMessage()', '->getCode()', '->getFile()', '->getLine()',
      '->bindParam(parameter, variable)', '->execute(params)',
      '->fetch(mode)', '->fetchAll(mode)', '->fetchColumn()', '->rowCount()',
      '->query(sql)', '->prepare(sql)', '->lastInsertId()', '->beginTransaction()',
      '->commit()', '->rollBack()',
    ],
  },

  ruby: {
    keywords: [
      'BEGIN', 'END', 'alias', 'and', 'begin', 'break', 'case', 'class',
      'def', 'defined?', 'do', 'else', 'elsif', 'end', 'ensure', 'false',
      'for', 'if', 'in', 'module', 'next', 'nil', 'not', 'or', 'redo',
      'rescue', 'retry', 'return', 'self', 'super', 'then', 'true', 'undef',
      'unless', 'until', 'when', 'while', 'yield', 'require', 'require_relative',
      'attr_accessor', 'attr_reader', 'attr_writer', 'include', 'extend',
    ],
    types: ['Array', 'Hash', 'String', 'Integer', 'Float', 'Symbol', 'Range', 'Struct', 'Proc', 'Time', 'File', 'IO', 'Exception', 'StandardError', 'Set', 'Enumerator'],
    constants: ['true', 'false', 'nil', '__FILE__', '__LINE__', 'ENV', 'ARGV', 'STDIN', 'STDOUT', 'STDERR', 'Float::INFINITY'],
    functions: [
      'puts(object)', 'print(object)', 'p(object)', 'pp(object)',
      'gets(chomp)', 'readline()', 'sleep(seconds)',
      'Array(object)', 'Hash(object)', 'String(object)', 'Integer(object)',
      'Float(object)', 'rand(max)', 'srand(seed)',
      'raise(exception)', 'fail(message)', 'loop { block }',
      'format(format, args)', 'sprintf(format, args)', 'printf(format, args)',
      'require(name)', 'require_relative(name)', 'load(filename)',
      'lambda { block }', 'proc { block }',
      'gets.chomp', 'puts', 'loop', 'catch(symbol)', 'throw(symbol)',
      'block_given?', 'freeze', 'dup', 'clone', 'equal?(other)', 'nil?',
    ],
    snippets: [
      { label: 'def', body: 'def ${1:name}(${2:args})\n  ${3:# body}\nend' },
      { label: 'class', body: 'class ${1:Name}\n  def initialize(${2:args})\n    ${3}\n  end\nend' },
      { label: 'if', body: 'if ${1:condition}\n  ${2}\nend' },
      { label: 'unless', body: 'unless ${1:condition}\n  ${2}\nend' },
      { label: 'each', body: '${1:items}.each do |${2:item}|\n  ${3}\nend' },
      { label: 'eachwithindex', body: '${1:items}.each_with_index do |${2:item}, ${3:index}|\n  ${4}\nend' },
      { label: 'while', body: 'while ${1:condition}\n  ${2}\nend' },
      { label: 'case', body: 'case ${1:value}\nwhen ${2:option}\n  ${3}\nelse\n  ${4}\nend' },
      { label: 'begin', body: 'begin\n  ${1}\nrescue ${2:StandardError} => ${3:error}\n  ${4}\nend' },
      { label: 'puts', body: 'puts ${1:value}' },
      { label: 'hash', body: '${1:options} = {\n  ${2:key}: ${3:value}\n}' },
    ],
    members: [
      '.length', '.size', '.empty?', '.nil?', '.freeze', '.dup', '.clone',
      '.push(value)', '.pop', '.shift', '.unshift(value)', '.first', '.last',
      '.include?(value)', '.index(value)', '.each { |x| }', '.map { |x| }',
      '.select { |x| }', '.reject { |x| }', '.reduce(initial) { |acc, x| }',
      '.sort', '.sort_by { |x| }', '.reverse', '.join(separator)',
      '.split(pattern)', '.strip', '.chomp', '.upcase', '.downcase',
      '.capitalize', '.gsub(pattern, replacement)', '.sub(pattern, replacement)',
      '.start_with?(prefix)', '.end_with?(suffix)', '.tr(from, to)',
      '.to_s', '.to_i', '.to_f', '.to_a', '.to_h', '.to_sym', '.inspect',
      '.keys', '.values', '.fetch(key)', '.store(key, value)',
      '.merge(other)', '.delete(key)', '.key?(key)', '.each_pair { |k, v| }',
    ],
  },

  kotlin: {
    keywords: [
      'as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for',
      'fun', 'if', 'in', 'interface', 'is', 'null', 'object', 'package',
      'return', 'super', 'this', 'throw', 'true', 'try', 'typealias',
      'val', 'var', 'when', 'while', 'by', 'catch', 'constructor', 'delegate',
      'dynamic', 'field', 'file', 'finally', 'get', 'import', 'init', 'param',
      'property', 'receiver', 'set', 'setparam', 'where', 'actual', 'abstract',
      'annotation', 'companion', 'const', 'crossinline', 'data', 'enum',
      'expect', 'external', 'final', 'infix', 'inline', 'inner', 'internal',
      'lateinit', 'noinline', 'open', 'operator', 'out', 'override', 'private',
      'protected', 'public', 'reified', 'sealed', 'suspend', 'tailrec',
      'vararg', 'it',
    ],
    types: ['String', 'Int', 'Long', 'Double', 'Float', 'Boolean', 'Char', 'Byte', 'Short', 'Unit', 'Any', 'Nothing', 'List', 'MutableList', 'Set', 'MutableSet', 'Map', 'MutableMap', 'Array', 'Pair', 'Triple', 'Sequence', 'Exception', 'Throwable', 'Regex', 'StringBuilder'],
    constants: ['true', 'false', 'null', 'Int.MAX_VALUE', 'Int.MIN_VALUE', 'Long.MAX_VALUE', 'Double.MAX_VALUE', 'Double.NaN', 'PI', 'E'],
    functions: [
      'println(message)', 'print(message)', 'readLine()', 'readln()',
      'arrayOf(elements)', 'listOf(elements)', 'mutableListOf(elements)',
      'setOf(elements)', 'mutableSetOf(elements)', 'mapOf(pairs)',
      'mutableMapOf(pairs)', 'emptyList()', 'emptyMap()', 'emptySet()',
      'intArrayOf(elements)', 'charArrayOf(elements)',
      'maxOf(a, b)', 'minOf(a, b)', 'abs(x)', 'sqrt(x)', 'pow(x, y)',
      'floor(x)', 'ceil(x)', 'round(x)', 'require(condition)', 'check(condition)',
      'error(message)', 'TODO()', 'repeat(times) { }', 'run { }', 'let { }',
      'also { }', 'apply { }', 'with(receiver) { }', 'takeIf { }', 'takeUnless { }',
      'lazy { }', 'runCatching { }',
    ],
    snippets: [
      { label: 'main', body: 'fun main() {\n    ${1:println("Hello, world!")}\n}' },
      { label: 'fun', body: 'fun ${1:name}(${2:args}): ${3:Unit} {\n    ${4}\n}' },
      { label: 'class', body: 'class ${1:Name}(${2:val property: Type}) {\n    ${3}\n}' },
      { label: 'data', body: 'data class ${1:Name}(\n    ${2:val property: Type},\n)' },
      { label: 'for', body: 'for (${1:item} in ${2:items}) {\n    ${3}\n}' },
      { label: 'while', body: 'while (${1:condition}) {\n    ${2}\n}' },
      { label: 'if', body: 'if (${1:condition}) {\n    ${2}\n}' },
      { label: 'when', body: 'when (${1:value}) {\n    ${2:option} -> ${3}\n    else -> ${4}\n}' },
      { label: 'try', body: 'try {\n    ${1}\n} catch (${2:e: Exception}) {\n    ${3}\n}' },
      { label: 'list', body: 'val ${1:list} = listOf(${2:elements})' },
      { label: 'map', body: 'val ${1:map} = mapOf(${2:key to value})' },
    ],
    members: [
      '.length', '.size', '.isEmpty()', '.isNotEmpty()', '.uppercase()',
      '.lowercase()', '.trim()', '.trimIndent()', '.split(delimiter)',
      '.substring(start, end)', '.replace(old, new)', '.startsWith(prefix)',
      '.endsWith(suffix)', '.contains(substring)', '.indexOf(string)',
      '.toInt()', '.toDouble()', '.toLong()', '.toBoolean()', '.toString()',
      '.toCharArray()', '.reversed()', '.repeat(n)', '.padStart(length)',
      '.padEnd(length)', '.first()', '.last()', '.getOrNull(index)',
      '.add(element)', '.addAll(elements)', '.remove(element)', '.removeAt(index)',
      '.clear()', '.forEach { }', '.map { }', '.filter { }', '.firstOrNull { }',
      '.sorted()', '.sortedBy { }', '.distinct()', '.take(n)', '.drop(n)',
      '.joinToString(separator)', '.sum()', '.average()', '.maxOrNull()',
      '.minOrNull()', '.getOrPut(key) { }', '.getValue(key)', '.put(key, value)',
      '.keys', '.values', '.entries', '.containsKey(key)', '.getOrDefault(key, default)',
    ],
  },

  swift: {
    keywords: [
      'as', 'associatedtype', 'break', 'case', 'catch', 'class', 'continue',
      'default', 'defer', 'deinit', 'do', 'else', 'enum', 'extension',
      'fallthrough', 'false', 'fileprivate', 'for', 'func', 'guard', 'if',
      'import', 'in', 'init', 'inout', 'internal', 'is', 'let', 'nil',
      'open', 'operator', 'private', 'protocol', 'public', 'repeat',
      'rethrows', 'return', 'self', 'Self', 'static', 'struct', 'subscript',
      'super', 'switch', 'throw', 'throws', 'true', 'try', 'typealias',
      'var', 'where', 'while', 'async', 'await', 'some', 'any', 'guard',
    ],
    types: ['String', 'Int', 'Double', 'Float', 'Bool', 'Character', 'Array', 'Dictionary', 'Set', 'Optional', 'Result', 'Error', 'Any', 'AnyObject', 'Void', 'Range', 'ClosedRange', 'Tuple', 'Date', 'URL', 'Data'],
    constants: ['true', 'false', 'nil', 'Int.max', 'Int.min', 'Double.infinity', 'Double.pi', 'Float.pi'],
    functions: [
      'print(items, separator, terminator)', 'debugPrint(items)',
      'readLine()', 'String(describing: value)', 'String(repeating: count:)',
      'Int(string)', 'Double(string)', 'abs(x)', 'min(a, b)', 'max(a, b)',
      'sqrt(x)', 'pow(a, b)', 'floor(x)', 'ceil(x)', 'round(x)',
      'stride(from: to: by:)', 'zip(sequence1, sequence2)',
      'type(of: value)', 'assert(condition)', 'precondition(condition)',
      'fatalError(message)', 'dump(value)', 'swap(&a, &b)',
      'Array(repeating: count:)', 'Dictionary(uniqueKeysWithValues:)',
      'abs(x)', 'sequence(first: next:)', 'withUnsafePointer(to:)',
    ],
    snippets: [
      { label: 'func', body: 'func ${1:name}(${2:args}) -> ${3:ReturnType} {\n    ${4}\n}' },
      { label: 'class', body: 'class ${1:Name} {\n    init(${2:args}) {\n        ${3}\n    }\n}' },
      { label: 'struct', body: 'struct ${1:Name} {\n    let ${2:property}: ${3:String}\n}' },
      { label: 'guard', body: 'guard let ${1:value} = ${2:optional} else {\n    ${3:return}\n}' },
      { label: 'iflet', body: 'if let ${1:value} = ${2:optional} {\n    ${3}\n}' },
      { label: 'for', body: 'for ${1:item} in ${2:collection} {\n    ${3}\n}' },
      { label: 'while', body: 'while ${1:condition} {\n    ${2}\n}' },
      { label: 'switch', body: 'switch ${1:value} {\ncase ${2:pattern}:\n    ${3}\ndefault:\n    ${4:break}\n}' },
      { label: 'print', body: 'print(${1:value})' },
      { label: 'dowhile', body: 'repeat {\n    ${1}\n} while ${2:condition}' },
    ],
    members: [
      '.count', '.isEmpty', '.first', '.last', '.append(element)',
      '.insert(element, at: index)', '.remove(at: index)', '.removeFirst()',
      '.removeLast()', '.sorted()', '.sorted(by:)', '.reversed()',
      '.contains(element)', '.index(of: element)', '.map { }', '.filter { }',
      '.reduce(initial) { }', '.forEach { }', '.prefix(n)', '.suffix(n)',
      '.joined(separator:)', '.enumerated()', '.firstIndex(of: element)',
      '.uppercased()', '.lowercased()', '.trimmingCharacters(in:)',
      '.split(separator:)', '.hasPrefix(prefix)', '.hasSuffix(suffix)',
      '.replacingOccurrences(of:with:)', '.components(separatedBy:)',
      '.joined(separator:)', '.description', '.startIndex', '.endIndex',
      '.keys', '.values', '.updateValue(value, forKey:)', '.removeValue(forKey:)',
      '.merging(other) { }', '.mapValues { }',
    ],
  },

  sql: {
    keywords: [
      'ALL', 'ALTER', 'AND', 'AS', 'ASC', 'BETWEEN', 'BY', 'CASE', 'CHECK',
      'COLUMN', 'COMMIT', 'CONSTRAINT', 'CREATE', 'CROSS', 'DATABASE',
      'DEFAULT', 'DELETE', 'DESC', 'DISTINCT', 'DROP', 'ELSE', 'END',
      'EXCEPT', 'EXISTS', 'FOREIGN', 'FROM', 'FULL', 'GROUP', 'HAVING',
      'IN', 'INDEX', 'INNER', 'INSERT', 'INTO', 'IS', 'JOIN', 'KEY', 'LEFT',
      'LIKE', 'LIMIT', 'NOT', 'NULL', 'OFFSET', 'ON', 'OR', 'ORDER', 'OUTER',
      'PRIMARY', 'REFERENCES', 'RIGHT', 'ROLLBACK', 'SELECT', 'SET', 'TABLE',
      'THEN', 'TRANSACTION', 'UNION', 'UNIQUE', 'UPDATE', 'VALUES', 'VIEW',
      'WHEN', 'WHERE', 'WITH',
    ],
    types: ['INTEGER', 'TEXT', 'REAL', 'BLOB', 'NUMERIC', 'BOOLEAN', 'DATE', 'DATETIME', 'VARCHAR', 'CHAR', 'DECIMAL', 'BIGINT', 'SMALLINT'],
    constants: ['NULL', 'TRUE', 'FALSE', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP'],
    functions: [
      'COUNT(expression)', 'SUM(expression)', 'AVG(expression)',
      'MIN(expression)', 'MAX(expression)', 'GROUP_CONCAT(expression)',
      'ABS(x)', 'ROUND(x, digits)', 'RANDOM()', 'LENGTH(string)',
      'LOWER(string)', 'UPPER(string)', 'TRIM(string)', 'LTRIM(string)',
      'RTRIM(string)', 'SUBSTR(string, start, length)', 'REPLACE(string, from, to)',
      'INSTR(string, substring)', 'COALESCE(value, fallback)',
      'IFNULL(value, fallback)', 'NULLIF(a, b)', 'CAST(value AS type)',
      'DATE(timestring)', 'DATETIME(timestring)', 'STRFTIME(format, timestring)',
      'JULIANDAY(timestring)', 'PRINTF(format, args...)', 'TYPEOF(value)',
      'ROW_NUMBER()', 'RANK()', 'DENSE_RANK()', 'LAG(value, offset)',
      'LEAD(value, offset)', 'FIRST_VALUE(value)', 'LAST_VALUE(value)',
    ],
    snippets: [
      { label: 'select', body: 'SELECT ${1:*}\nFROM ${2:table}\nWHERE ${3:condition};' },
      { label: 'insert', body: 'INSERT INTO ${1:table} (${2:columns})\nVALUES (${3:values});' },
      { label: 'update', body: 'UPDATE ${1:table}\nSET ${2:column} = ${3:value}\nWHERE ${4:condition};' },
      { label: 'delete', body: 'DELETE FROM ${1:table}\nWHERE ${2:condition};' },
      { label: 'create', body: 'CREATE TABLE ${1:table} (\n    ${2:id} INTEGER PRIMARY KEY,\n    ${3:column} ${4:TEXT}\n);' },
      { label: 'alter', body: 'ALTER TABLE ${1:table}\nADD COLUMN ${2:column} ${3:TEXT};' },
      { label: 'join', body: 'SELECT ${1:*}\nFROM ${2:a}\nINNER JOIN ${3:b} ON ${2:a}.${4:id} = ${3:b}.${5:a_id};' },
      { label: 'groupby', body: 'SELECT ${1:column}, COUNT(*)\nFROM ${2:table}\nGROUP BY ${1:column}\nHAVING COUNT(*) > ${3:1};' },
      { label: 'case', body: 'CASE\n    WHEN ${1:condition} THEN ${2:result}\n    ELSE ${3:fallback}\nEND' },
      { label: 'cte', body: 'WITH ${1:name} AS (\n    SELECT ${2:*}\n    FROM ${3:table}\n)\nSELECT * FROM ${1:name};' },
    ],
  },

  shell: {
    keywords: [
      'case', 'do', 'done', 'elif', 'else', 'esac', 'fi', 'for', 'function',
      'if', 'in', 'then', 'until', 'while', 'select', 'time', 'coproc',
    ],
    types: ['local', 'declare', 'typeset', 'export', 'readonly'],
    constants: ['$HOME', '$PATH', '$PWD', '$USER', '$SHELL', '$RANDOM', '$#', '$?', '$0', '$1', '$@', '$*', '$$'],
    functions: [
      'echo "text"', 'printf "format" args', 'read -r variable',
      'cd path', 'pwd', 'ls -la', 'cat file', 'head -n N file',
      'tail -n N file', 'grep pattern file', 'sed "s/old/new/g" file',
      'awk "{print \\$1}" file', 'cut -d delimiter -f fields',
      'sort file', 'uniq', 'wc -l file', 'tr from to', 'find path -name pattern',
      'xargs command', 'chmod mode file', 'chown user file', 'cp source dest',
      'mv source dest', 'rm path', 'mkdir -p path', 'rmdir path',
      'touch file', 'ln -s target link', 'du -sh path', 'df -h',
      'export NAME=value', 'source script', 'alias name=command',
      'unset variable', 'env', 'set -e', 'set -x', 'set -o pipefail',
      'test condition', 'true', 'false', 'date', 'sleep seconds',
      'basename path', 'dirname path', 'realpath path', 'mktemp',
      'grep -r pattern path', 'grep -v pattern', 'grep -E pattern',
      'sed -i "s/old/new/g" file', 'head -c bytes file', 'tee file',
      'diff file1 file2', 'tar -czf archive.tar.gz dir', 'gzip file',
      'curl -s url', 'wget url', 'ps aux', 'kill -9 pid', 'jobs', 'wait',
    ],
    snippets: [
      { label: 'shebang', body: '#!/usr/bin/env bash\nset -euo pipefail\n\n${1}' },
      { label: 'if', body: 'if [[ ${1:condition} ]]; then\n    ${2}\nfi' },
      { label: 'ifelse', body: 'if [[ ${1:condition} ]]; then\n    ${2}\nelse\n    ${3}\nfi' },
      { label: 'for', body: 'for ${1:item} in ${2:items}; do\n    ${3}\ndone' },
      { label: 'while', body: 'while [[ ${1:condition} ]]; do\n    ${2}\ndone' },
      { label: 'case', body: 'case "${1:value}" in\n    ${2:pattern})\n        ${3}\n        ;;\n    *)\n        ${4}\n        ;;\nesac' },
      { label: 'func', body: '${1:name}() {\n    ${2}\n}' },
      { label: 'readloop', body: 'while IFS= read -r ${1:line}; do\n    ${2}\ndone < ${3:file}' },
    ],
  },
};

/**
 * Import statements, per language.
 *
 * Without this, typing `import java.` offers nothing useful: the completion
 * provider reads the dot as member access and answers with *methods*, which is
 * exactly backwards. An import line is a namespace tree of its own, so it gets
 * its own catalogue and its own branch in the provider.
 *
 * `paths` holds complete names. The provider walks one segment at a time — for
 * `import java.ut` it collects every path under `java.` and offers the next
 * segment (`util`, `io`, `lang`, …) — and lets Monaco filter by what was typed.
 */
export interface ImportCatalog {
  /** Full importable names, e.g. `java.util.Scanner` or `std::io::Read`. */
  paths: string[];
  /** Regex source, anchored with `^`, matching the start of an import line. */
  trigger: string;
  /** For `from X import Y` syntax: group 1 captures the module. */
  fromTrigger?: string;
  /** Segment separator. An empty string treats each path as one atom. */
  separator?: string;
  /** Whether a path's final segment names a type rather than a package. */
  types?: boolean;
}

export const LANGUAGE_IMPORTS: Record<string, ImportCatalog> = {
  java: {
    trigger: '^\\s*(?:import|package)\\s+(?:static\\s+)?',
    types: true,
    paths: [
      'java.lang.String', 'java.lang.Math', 'java.lang.System', 'java.lang.Object',
      'java.lang.Integer', 'java.lang.Double', 'java.lang.Long', 'java.lang.Boolean',
      'java.lang.Character', 'java.lang.StringBuilder', 'java.lang.Thread',
      'java.lang.Exception', 'java.lang.RuntimeException', 'java.lang.Iterable',
      'java.util.Scanner', 'java.util.List', 'java.util.ArrayList', 'java.util.LinkedList',
      'java.util.Map', 'java.util.HashMap', 'java.util.LinkedHashMap', 'java.util.TreeMap',
      'java.util.Set', 'java.util.HashSet', 'java.util.LinkedHashSet', 'java.util.TreeSet',
      'java.util.Queue', 'java.util.Deque', 'java.util.ArrayDeque', 'java.util.PriorityQueue',
      'java.util.Collections', 'java.util.Arrays', 'java.util.Optional', 'java.util.Random',
      'java.util.Iterator', 'java.util.Comparator', 'java.util.Objects', 'java.util.UUID',
      'java.util.Date', 'java.util.Calendar', 'java.util.StringTokenizer', 'java.util.BitSet',
      'java.util.stream.Stream', 'java.util.stream.Collectors', 'java.util.stream.IntStream',
      'java.util.function.Function', 'java.util.function.Supplier', 'java.util.function.Consumer',
      'java.util.function.Predicate', 'java.util.function.BiFunction',
      'java.util.function.UnaryOperator', 'java.util.concurrent.ConcurrentHashMap',
      'java.util.concurrent.ExecutorService', 'java.util.concurrent.Executors',
      'java.util.concurrent.TimeUnit', 'java.util.concurrent.atomic.AtomicInteger',
      'java.io.File', 'java.io.IOException', 'java.io.BufferedReader', 'java.io.BufferedWriter',
      'java.io.InputStreamReader', 'java.io.OutputStreamWriter', 'java.io.FileReader',
      'java.io.FileWriter', 'java.io.PrintWriter', 'java.io.InputStream', 'java.io.OutputStream',
      'java.io.FileNotFoundException', 'java.io.UncheckedIOException',
      'java.math.BigInteger', 'java.math.BigDecimal', 'java.math.RoundingMode',
      'java.text.DecimalFormat', 'java.text.SimpleDateFormat', 'java.text.NumberFormat',
      'java.time.LocalDate', 'java.time.LocalTime', 'java.time.LocalDateTime',
      'java.time.Duration', 'java.time.Period', 'java.time.Instant', 'java.time.ZonedDateTime',
      'java.time.format.DateTimeFormatter',
      'java.nio.file.Files', 'java.nio.file.Paths', 'java.nio.file.Path',
      'java.net.URL', 'java.net.URI', 'java.net.http.HttpClient',
      'java.sql.Connection', 'java.sql.DriverManager', 'java.sql.ResultSet',
      'java.sql.Statement', 'java.sql.PreparedStatement', 'java.sql.SQLException',
      'java.security.MessageDigest',
      'javax.swing.JFrame', 'javax.swing.JPanel', 'javax.swing.JButton',
      'javax.swing.JLabel', 'javax.swing.JTextField',
    ],
  },

  python: {
    trigger: '^\\s*(?:import|from)\\s+',
    fromTrigger: '^\\s*from\\s+([\\w.]+)\\s+import\\s+',
    paths: [
      'os', 'os.path', 'os.getcwd', 'os.environ', 'os.listdir', 'os.makedirs',
      'os.remove', 'os.system',
      'sys', 'sys.argv', 'sys.exit', 'sys.stdin', 'sys.stdout', 'sys.stderr',
      'sys.path', 'sys.maxsize', 'sys.version',
      'math', 'math.sqrt', 'math.pow', 'math.pi', 'math.e', 'math.floor',
      'math.ceil', 'math.sin', 'math.cos', 'math.tan', 'math.log', 'math.exp',
      'math.fabs', 'math.inf', 'math.gcd',
      'random', 'random.randint', 'random.choice', 'random.shuffle',
      'random.random', 'random.randrange', 'random.sample', 'random.seed',
      'statistics', 'statistics.mean', 'statistics.median', 'statistics.mode',
      'collections', 'collections.OrderedDict', 'collections.defaultdict',
      'collections.Counter', 'collections.deque', 'collections.namedtuple',
      'itertools', 'itertools.product', 'itertools.permutations',
      'itertools.combinations', 'itertools.chain', 'itertools.count',
      'itertools.cycle', 'itertools.groupby', 'itertools.islice',
      'functools', 'functools.reduce', 'functools.lru_cache', 'functools.partial',
      'functools.wraps',
      'json', 'json.dumps', 'json.loads', 'json.dump', 'json.load',
      're', 're.compile', 're.match', 're.search', 're.findall', 're.sub', 're.split',
      'time', 'time.time', 'time.sleep', 'time.perf_counter',
      'datetime', 'datetime.datetime', 'datetime.date', 'datetime.time',
      'datetime.timedelta', 'calendar',
      'string', 'string.ascii_lowercase', 'string.ascii_uppercase',
      'string.digits', 'string.punctuation',
      'io', 'io.StringIO', 'io.BytesIO', 'pathlib', 'pathlib.Path',
      'subprocess', 'subprocess.run', 'subprocess.Popen',
      'typing', 'typing.List', 'typing.Dict', 'typing.Set', 'typing.Tuple',
      'typing.Optional', 'typing.Any', 'typing.Union', 'typing.Callable',
      'dataclasses', 'dataclasses.dataclass', 'dataclasses.field',
      'enum', 'enum.Enum', 'enum.IntEnum', 'enum.auto', 'abc',
      'csv', 'csv.reader', 'csv.writer', 'csv.DictReader',
      'sqlite3', 'threading', 'asyncio',
      'heapq', 'heapq.heappush', 'heapq.heappop', 'heapq.heapify',
      'heapq.nlargest', 'heapq.nsmallest',
      'bisect', 'bisect.bisect_left', 'bisect.bisect_right', 'bisect.insort',
      'copy', 'copy.deepcopy', 'hashlib', 'hmac', 'base64',
      'urllib.parse', 'urllib.request', 'urllib.error', 'http.client',
      'email', 'logging', 'unittest', 'fractions', 'fractions.Fraction',
      'decimal', 'decimal.Decimal', 'shutil', 'glob', 'tempfile',
      'argparse', 'contextlib', 'traceback', 'warnings', 'textwrap', 'pprint',
      'secrets', 'uuid', 'uuid.uuid4', 'zipfile', 'gzip', 'socket', 'struct',
      'array', 'queue', 'multiprocessing', 'platform', 'getpass', 'zoneinfo', 'pdb',
    ],
  },

  c: {
    trigger: '^\\s*#\\s*include\\s*[<"]?',
    separator: '',
    paths: [
      'stdio.h', 'stdlib.h', 'string.h', 'math.h', 'time.h', 'ctype.h',
      'assert.h', 'limits.h', 'stdint.h', 'stdbool.h', 'stddef.h', 'errno.h',
      'signal.h', 'stdarg.h', 'setjmp.h', 'locale.h', 'float.h', 'wchar.h',
      'wctype.h', 'complex.h', 'fenv.h', 'inttypes.h', 'tgmath.h',
    ],
  },

  cpp: {
    trigger: '^\\s*#\\s*include\\s*[<"]?',
    separator: '',
    paths: [
      'iostream', 'iomanip', 'ios', 'istream', 'ostream', 'fstream', 'sstream',
      'string', 'vector', 'list', 'deque', 'array', 'forward_list', 'map', 'set',
      'unordered_map', 'unordered_set', 'multimap', 'multiset', 'queue', 'stack',
      'priority_queue', 'algorithm', 'numeric', 'functional', 'memory', 'utility',
      'tuple', 'optional', 'variant', 'any', 'bitset', 'cmath', 'cstdio',
      'cstdlib', 'cstring', 'ctime', 'cctype', 'climits', 'cstdint', 'cstddef',
      'chrono', 'thread', 'mutex', 'atomic', 'future', 'random', 'regex',
      'type_traits', 'iterator', 'limits', 'stdexcept', 'exception', 'new',
      'typeinfo', 'initializer_list', 'complex', 'valarray', 'locale',
      'codecvt', 'filesystem', 'charconv', 'bit', 'bits/stdc++.h',
    ],
  },

  csharp: {
    trigger: '^\\s*using\\s+(?:static\\s+)?',
    paths: [
      'System', 'System.Console', 'System.Math', 'System.Text',
      'System.Text.StringBuilder', 'System.Text.Json', 'System.Text.RegularExpressions',
      'System.IO', 'System.IO.File', 'System.IO.StreamReader',
      'System.Collections', 'System.Collections.Generic',
      'System.Collections.Generic.List', 'System.Collections.Generic.Dictionary',
      'System.Linq', 'System.Threading', 'System.Threading.Tasks',
      'System.Net', 'System.Net.Http', 'System.Globalization',
      'System.Diagnostics', 'System.Runtime', 'System.Numerics',
      'System.Security.Cryptography', 'System.Data', 'System.Data.SqlClient',
    ],
  },

  go: {
    // Either the keyword form (`import "fmt"`, `import (`) or a bare quoted
    // path on its own line, which is how a grouped `import ( … )` block reads.
    trigger: '^\\s*import\\s+(?:\\(|\\w+\\s*)?"?|^\\s*"[^"]*$',
    separator: '/',
    paths: [
      'fmt', 'os', 'io', 'io/ioutil', 'bufio', 'strings', 'strconv', 'sort',
      'math', 'math/rand', 'math/big', 'math/bits', 'time', 'errors', 'bytes',
      'unicode', 'unicode/utf8', 'regexp', 'encoding/json', 'encoding/csv',
      'encoding/base64', 'encoding/hex', 'net', 'net/http', 'net/url',
      'path', 'path/filepath', 'sync', 'sync/atomic', 'context',
      'container/heap', 'container/list', 'crypto/sha256', 'database/sql',
      'reflect', 'runtime', 'log', 'flag', 'text/template', 'testing',
    ],
  },

  rust: {
    trigger: '^\\s*use\\s+',
    separator: '::',
    paths: [
      'std::collections::HashMap', 'std::collections::HashSet',
      'std::collections::BTreeMap', 'std::collections::BTreeSet',
      'std::collections::VecDeque',
      'std::io', 'std::io::Read', 'std::io::Write', 'std::io::BufRead',
      'std::io::BufReader', 'std::io::BufWriter',
      'std::fmt', 'std::fmt::Display', 'std::fmt::Debug',
      'std::fs', 'std::fs::File', 'std::env', 'std::env::args',
      'std::process', 'std::process::Command', 'std::process::exit',
      'std::cmp', 'std::cmp::Ordering', 'std::mem',
      'std::sync', 'std::sync::Arc', 'std::sync::Mutex', 'std::sync::atomic',
      'std::thread', 'std::time::Duration', 'std::time::Instant',
      'std::str::FromStr', 'std::num::ParseIntError', 'std::error::Error',
      'std::result::Result', 'std::option::Option', 'std::borrow::Cow',
      'std::iter::Iterator', 'std::convert::TryFrom',
      'std::path::Path', 'std::path::PathBuf',
    ],
  },

  php: {
    trigger: '^\\s*use\\s+',
    separator: '',
    paths: [
      'DateTime', 'DateTimeImmutable', 'DateInterval', 'DateTimeZone',
      'PDO', 'PDOStatement', 'Exception', 'RuntimeException',
      'InvalidArgumentException', 'LogicException', 'ArrayObject',
      'ArrayIterator', 'SplStack', 'SplQueue', 'SplFixedArray', 'SplObjectStorage',
      'Closure', 'Generator', 'stdClass', 'JsonSerializable', 'Countable',
      'IteratorAggregate', 'ArrayAccess', 'Traversable', 'Stringable',
    ],
  },

  ruby: {
    trigger: '^\\s*(?:require|require_relative|load)\\s+[\'"]?',
    separator: '',
    paths: [
      'json', 'set', 'date', 'time', 'csv', 'yaml', 'net/http', 'uri',
      'open-uri', 'securerandom', 'digest', 'base64', 'stringio', 'tempfile',
      'fileutils', 'pathname', 'benchmark', 'logger', 'optparse', 'openssl',
      'socket', 'bigdecimal', 'matrix', 'prime', 'forwardable', 'singleton',
      'ostruct', 'abbrev', 'cgi', 'erb', 'shellwords', 'timeout',
    ],
  },

  kotlin: {
    trigger: '^\\s*import\\s+',
    types: true,
    paths: [
      'kotlin.math', 'kotlin.math.abs', 'kotlin.math.max', 'kotlin.math.min',
      'kotlin.math.sqrt', 'kotlin.math.pow', 'kotlin.math.floor', 'kotlin.math.ceil',
      'kotlin.math.round', 'kotlin.text', 'kotlin.collections',
      'kotlin.sequences', 'kotlin.io', 'kotlin.random', 'kotlin.time',
      'kotlin.system', 'kotlin.concurrent', 'java.util', 'java.util.Scanner',
      'java.io', 'java.time', 'java.nio.file', 'java.math', 'java.util.stream',
    ],
  },

  swift: {
    trigger: '^\\s*import\\s+',
    separator: '',
    paths: [
      'Foundation', 'Swift', 'Dispatch', 'Combine', 'CoreData', 'SwiftUI',
      'UIKit', 'CoreFoundation', 'CoreGraphics', 'MapKit', 'AVFoundation',
      'os', 'CryptoKit', 'Network', 'GameplayKit', 'SpriteKit', 'Metal',
    ],
  },
};

/** Languages that have Monaco's built-in language worker (TS/JS/JSON only). */
export const MONACO_WORKER_LANGUAGES = new Set([
  'typescript', 'typescriptreact', 'javascript', 'javascriptreact',
  'json', 'jsonc',
]);

